
[zsh.files]
zshrc = "~/.zshrc"

[i3.files]
i3 = "~/.config/i3/config"

[vim.files]
vimrc = "~/.config/nvim/init.vim"
be256_vim = "~/.config/nvim/colors/be256.vim"

[kitty.files]
kitty_conf = "~/.config/kitty/kitty.conf"

[dunst.files]
dunstrc = "~/.config/dunst/dunstrc"

[rofi.files]
rofi = "~/.config/rofi/config"

[X11.files]
Xdefaults = "~/./Xdefaults"

[starship.files]
starship_toml = "~/.config/starship.toml"

[dir_colors.files]
dir_colors = "~/.dir_colors"
